name: Deploy Lista de espera

on:
  workflow_dispatch:
    inputs:
      CHAT_URL:
        description: 'Link da lista de espera (Whatsapp, etc.)'
        required: true
        default: 'https://chat.whatsapp.com/Ku1LN5Uk8UAEs7gBkRrdwE'
      STATUS_LISTA:
        description: 'Status da lista de espera (ex: Vagas encerradas)'
        required: true
        default: 'Vagas encerradas'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace placeholders with manual inputs
        run: |
          sed -i 's|{{ CHAT_URL }}|${{ github.event.inputs.CHAT_URL }}|g' index-lista.html
          sed -i 's|{{ STATUS_LISTA }}|${{ github.event.inputs.STATUS_LISTA }}|g' index-lista.html
          # Copy lista de espera as main page
          cp index-lista.html index.html

      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Post deployment summary
        run: 'echo "🚀 Deploy concluído! Acesse a página em: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY'

  approval:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      # O environment do GitHub requer aprovação manual antes de continuar
      # Configure o environment "production" nas configurações do repositório
    steps:
      - name: Approval step
        run: echo "Aguardando aprovação para deploy em produção..."

  deploy-to-s3:
    needs: approval
    runs-on: ubuntu-latest
    if: ${{ needs.approval.result == 'success' }}
    env:
      AWS_REGION: sa-east-1
      BUCKET_NAME: ${{ vars.TF_VAR_bucket_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace placeholders with manual inputs
        run: |
          sed -i 's|{{ CHAT_URL }}|${{ github.event.inputs.CHAT_URL }}|g' index-lista.html
          sed -i 's|{{ STATUS_LISTA }}|${{ github.event.inputs.STATUS_LISTA }}|g' index-lista.html
          # Copy lista de espera as main page
          cp index-lista.html index.html

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gha-deploy-role
          aws-region: sa-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://$BUCKET_NAME/ --delete --exclude ".git/*" --exclude ".github/*"  --exclude "terraform/*" --exclude ".gitignore*" --exclude "images/*"
          echo "✅ Copy successful!" >> $GITHUB_STEP_SUMMARY
          S3_WEBSITE_URL="http://${BUCKET_NAME}.s3-website-sa-east-1.amazonaws.com"
          echo "🌐 S3 Website URL: $S3_WEBSITE_URL" >> $GITHUB_STEP_SUMMARY

      - name: Unpublish GitHub Pages
        if: always()
        run: |
          gh api --method DELETE repos/${{ github.repository }}/pages --silent || echo "Nenhuma publicação ativa do GitHub Pages para remover."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Cloudflare Custom Domain in Summary
        run: |
          echo "🌐 Cloudflare Custom Domain: https://${CUSTOM_DOMAIN}.${DOMAIN}" >> $GITHUB_STEP_SUMMARY
        env:
          CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
          DOMAIN: ${{ vars.DOMAIN }}